<?php
	/**
	 * Code source de la classe GestiondoublonTest.
	 *
	 * PHP 5.3
	 *
	 * @package app.Test.Case.Model
	 * @license CeCiLL V2 (http://www.cecill.info/licences/Licence_CeCILL_V2-fr.html)
	 */
	App::uses( 'Gestiondoublon', 'Model' );

	/**
	 * La classe GestiondoublonTest ...
	 *
	 * @package app.Test.Case.Model
	 */
	class GestiondoublonTest extends CakeTestCase
	{
		/**
		 * Fixtures utilisés.
		 *
		 * @var array
		 */
		public $fixtures = array(
			'app.Adresse',
			'app.Adressefoyer',
			'app.Calculdroitrsa',
			'app.Detailcalculdroitrsa',
			'app.Detaildroitrsa',
			'app.Dossier',
			'app.Foyer',
			'app.Personne',
			'app.PersonneReferent',
			'app.Prestation',
			'app.Referent',
			'app.Situationdossierrsa',
			'app.Structurereferente',
			'app.User',
		);

		public $emptySearch = array(
			'joins' => array(
				0 => array(
					'table' => '"adressesfoyers"',
					'alias' => 'Adressefoyer',
					'type' => 'LEFT OUTER',
					'conditions' => '"Adressefoyer"."foyer_id" = "Foyer"."id" AND (("Adressefoyer"."id" IS NULL) OR ("Adressefoyer"."id" IN ( SELECT "adressesfoyers"."id" AS adressesfoyers__id FROM adressesfoyers AS adressesfoyers   WHERE "adressesfoyers"."foyer_id" = "Foyer"."id" AND "adressesfoyers"."rgadr" = \'01\'   ORDER BY "adressesfoyers"."dtemm" DESC  LIMIT 1 )))',
				),
				1 => array(
					'table' => '"dossiers"',
					'alias' => 'Dossier',
					'type' => 'INNER',
					'conditions' => '"Foyer"."dossier_id" = "Dossier"."id"',
				),
				2 => array(
					'table' => '"personnes"',
					'alias' => 'Personne',
					'type' => 'INNER',
					'conditions' => '"Personne"."foyer_id" = "Foyer"."id"',
				),
				3 => array(
					'table' => '"adresses"',
					'alias' => 'Adresse',
					'type' => 'LEFT OUTER',
					'conditions' => '"Adressefoyer"."adresse_id" = "Adresse"."id"',
				),
				4 => array(
					'table' => '"situationsdossiersrsa"',
					'alias' => 'Situationdossierrsa',
					'type' => 'LEFT OUTER',
					'conditions' => '"Situationdossierrsa"."dossier_id" = "Dossier"."id"',
				),
				5 => array(
					'table' => '"prestations"',
					'alias' => 'Prestation',
					'type' => 'LEFT OUTER',
					'conditions' => '"Prestation"."personne_id" = "Personne"."id" AND "Prestation"."natprest" = \'RSA\'',
				),
				6 => array(
					'table' => '"personnes"',
					'alias' => 'Demandeur',
					'type' => 'LEFT OUTER',
					'conditions' => '"Demandeur"."foyer_id" = "Foyer"."id" AND (("Demandeur"."id" IN ( SELECT "prestations"."personne_id" FROM prestations WHERE "prestations"."personne_id" = "Demandeur"."id" AND "prestations"."natprest" = \'RSA\' AND "prestations"."rolepers" = \'DEM\' ORDER BY "prestations"."personne_id" ASC LIMIT 1 )) OR ("Demandeur"."id" IS NULL))',
				),
				7 => array(
					'table' => 'personnes',
					'alias' => 'p2',
					'type' => 'INNER',
					'foreignKey' => false,
					'conditions' => array(
						0 => 'Personne.id <> p2.id',
						1 => 'Personne.foyer_id <> p2.foyer_id',
						'OR' => array(
							0 => array(
								0 => 'nir_correct13(Personne.nir)',
								1 => 'nir_correct13(p2.nir)',
								2 => 'SUBSTRING( TRIM( BOTH \' \' FROM Personne.nir ) FROM 1 FOR 13 ) = SUBSTRING( TRIM( BOTH \' \' FROM p2.nir ) FROM 1 FOR 13 )',
								3 => 'Personne.dtnai = p2.dtnai',
							),
							1 => array(
								0 => 'UPPER(Personne.nom) = UPPER(p2.nom)',
								1 => 'UPPER(Personne.prenom) = UPPER(p2.prenom)',
								2 => 'Personne.dtnai = p2.dtnai',
							),
							/*2 => array(
								'difference(Personne.nom, p2.nom) >=' => 4,
								'difference(Personne.prenom, p2.prenom) >=' => 4,
								0 => 'Personne.dtnai = p2.dtnai',
							),*/
						),
					),
				),
				8 => array(
					'table' => 'foyers',
					'alias' => 'Foyer2',
					'type' => 'INNER',
					'foreignKey' => false,
					'conditions' => array(
						0 => 'p2.foyer_id = Foyer2.id',
					),
				),
				9 => array(
					'table' => '"adressesfoyers"',
					'alias' => 'Adressefoyer2',
					'type' => 'LEFT OUTER',
					'conditions' => '"Adressefoyer2"."foyer_id" = "Foyer2"."id" AND (("Adressefoyer2"."id" IS NULL) OR ("Adressefoyer2"."id" IN ( SELECT "adressesfoyers"."id" AS adressesfoyers__id FROM adressesfoyers AS adressesfoyers   WHERE "adressesfoyers"."foyer_id" = "Foyer2"."id" AND "adressesfoyers"."rgadr" = \'01\'   ORDER BY "adressesfoyers"."dtemm" DESC  LIMIT 1 )))'
				),
				10 => array(
					'table' => '"adresses"',
					'alias' => 'Adresse2',
					'type' => 'LEFT OUTER',
					'conditions' => '"Adressefoyer2"."adresse_id" = "Adresse2"."id"',
				),
				11 => array(
					'table' => 'dossiers',
					'alias' => 'Dossier2',
					'type' => 'INNER',
					'foreignKey' => false,
					'conditions' => array(
						0 => 'Foyer2.dossier_id = Dossier2.id',
						1 => 'Dossier2.id <> Dossier.id',
					),
				),
				12 => array(
					'table' => 'situationsdossiersrsa',
					'alias' => 'Situationdossierrsa2',
					'type' => 'INNER',
					'foreignKey' => false,
					'conditions' => array(
						0 => 'Situationdossierrsa2.dossier_id = Dossier2.id',
					),
				),
				13 => array(
					'table' => '"personnes"',
					'alias' => 'Demandeur2',
					'type' => 'LEFT OUTER',
					'conditions' => '"Demandeur2"."foyer_id" = "Foyer"."id" AND (("Demandeur2"."id" IN ( SELECT "prestations"."personne_id" FROM prestations WHERE "prestations"."personne_id" = "Demandeur2"."id" AND "prestations"."natprest" = \'RSA\' AND "prestations"."rolepers" = \'DEM\' ORDER BY "prestations"."personne_id" ASC LIMIT 1 )) OR ("Demandeur2"."id" IS NULL))',
				),
			),
			'conditions' => array(
				0 => array(
					'OR' => array(
						0 => 'Prestation.id IS NULL',
						'Prestation.rolepers' => array(
							0 => 'DEM',
							1 => 'CJT',
						),
					),
				),
				'Situationdossierrsa2.etatdosrsa' => array(
					0 => 'Z',
				),
			),
			'contain' => false,
			'order' => array(
				0 => 'Demandeur.nom',
				1 => 'Demandeur.prenom',
				2 => 'Dossier.matricule',
				3 => 'Dossier.dtdemrsa DESC',
				4 => 'Dossier.id',
			),
			'group' => array(
				0 => 'Foyer.id',
				1 => 'Foyer.dossier_id',
				2 => 'Foyer.sitfam',
				3 => 'Foyer.ddsitfam',
				4 => 'Foyer.typeocclog',
				5 => 'Foyer.mtvallocterr',
				6 => 'Foyer.mtvalloclog',
				7 => 'Foyer.contefichliairsa',
				8 => 'Foyer.mtestrsa',
				9 => 'Foyer.raisoctieelectdom',
				10 => 'Foyer.regagrifam',
				11 => 'Foyer.haspiecejointe',
				12 => 'Dossier.id',
				13 => 'Dossier.numdemrsa',
				14 => 'Dossier.dtdemrsa',
				15 => 'Dossier.dtdemrmi',
				16 => 'Dossier.numdepinsrmi',
				17 => 'Dossier.typeinsrmi',
				18 => 'Dossier.numcominsrmi',
				19 => 'Dossier.numagrinsrmi',
				20 => 'Dossier.numdosinsrmi',
				21 => 'Dossier.numcli',
				22 => 'Dossier.numorg',
				23 => 'Dossier.fonorg',
				24 => 'Dossier.matricule',
				25 => 'Dossier.statudemrsa',
				26 => 'Dossier.typeparte',
				27 => 'Dossier.ideparte',
				28 => 'Dossier.fonorgcedmut',
				29 => 'Dossier.numorgcedmut',
				30 => 'Dossier.matriculeorgcedmut',
				31 => 'Dossier.ddarrmut',
				32 => 'Dossier.codeposanchab',
				33 => 'Dossier.fonorgprenmut',
				34 => 'Dossier.numorgprenmut',
				35 => 'Dossier.dddepamut',
				36 => 'Dossier.detaildroitrsa_id',
				37 => 'Dossier.avispcgdroitrsa_id',
				38 => 'Dossier.organisme_id',
				39 => 'Dossier.id',
				40 => 'Dossier.numdemrsa',
				41 => 'Dossier.dtdemrsa',
				42 => 'Dossier.dtdemrmi',
				43 => 'Dossier.numdepinsrmi',
				44 => 'Dossier.typeinsrmi',
				45 => 'Dossier.numcominsrmi',
				46 => 'Dossier.numagrinsrmi',
				47 => 'Dossier.numdosinsrmi',
				48 => 'Dossier.numcli',
				49 => 'Dossier.numorg',
				50 => 'Dossier.fonorg',
				51 => 'Dossier.matricule',
				52 => 'Dossier.statudemrsa',
				53 => 'Dossier.typeparte',
				54 => 'Dossier.ideparte',
				55 => 'Dossier.fonorgcedmut',
				56 => 'Dossier.numorgcedmut',
				57 => 'Dossier.matriculeorgcedmut',
				58 => 'Dossier.ddarrmut',
				59 => 'Dossier.codeposanchab',
				60 => 'Dossier.fonorgprenmut',
				61 => 'Dossier.numorgprenmut',
				62 => 'Dossier.dddepamut',
				63 => 'Dossier.detaildroitrsa_id',
				64 => 'Dossier.avispcgdroitrsa_id',
				65 => 'Dossier.organisme_id',
				66 => 'Adresse.id',
				67 => 'Adresse.numvoie',
				68 => 'Adresse.typevoie',
				69 => 'Adresse.nomvoie',
				70 => 'Adresse.complideadr',
				71 => 'Adresse.compladr',
				72 => 'Adresse.lieudist',
				73 => 'Adresse.numcomrat',
				74 => 'Adresse.numcomptt',
				75 => 'Adresse.codepos',
				76 => 'Adresse.locaadr',
				77 => 'Adresse.pays',
				78 => 'Adresse.canton',
				79 => 'Adresse.typeres',
				80 => 'Adresse.topresetr',
				81 => 'Situationdossierrsa.id',
				82 => 'Situationdossierrsa.dossier_id',
				83 => 'Situationdossierrsa.etatdosrsa',
				84 => 'Situationdossierrsa.dtrefursa',
				85 => 'Situationdossierrsa.moticlorsa',
				86 => 'Situationdossierrsa.dtclorsa',
				87 => 'Situationdossierrsa.motirefursa',
				88 => 'Demandeur.id',
				89 => 'Demandeur.foyer_id',
				90 => 'Demandeur.qual',
				91 => 'Demandeur.nom',
				92 => 'Demandeur.prenom',
				93 => 'Demandeur.nomnai',
				94 => 'Demandeur.prenom2',
				95 => 'Demandeur.prenom3',
				96 => 'Demandeur.nomcomnai',
				97 => 'Demandeur.dtnai',
				98 => 'Demandeur.rgnai',
				99 => 'Demandeur.typedtnai',
				100 => 'Demandeur.nir',
				101 => 'Demandeur.topvalec',
				102 => 'Demandeur.sexe',
				103 => 'Demandeur.nati',
				104 => 'Demandeur.dtnati',
				105 => 'Demandeur.pieecpres',
				106 => 'Demandeur.idassedic',
				107 => 'Demandeur.numagenpoleemploi',
				108 => 'Demandeur.dtinscpoleemploi',
				109 => 'Demandeur.numfixe',
				110 => 'Demandeur.numport',
				111 => 'Demandeur.haspiecejointe',
				112 => 'Demandeur.email',
				113 => 'Foyer2.id',
				114 => 'Foyer2.dossier_id',
				115 => 'Foyer2.sitfam',
				116 => 'Foyer2.ddsitfam',
				117 => 'Foyer2.typeocclog',
				118 => 'Foyer2.mtvallocterr',
				119 => 'Foyer2.mtvalloclog',
				120 => 'Foyer2.contefichliairsa',
				121 => 'Foyer2.mtestrsa',
				122 => 'Foyer2.raisoctieelectdom',
				123 => 'Foyer2.regagrifam',
				124 => 'Foyer2.haspiecejointe',
				125 => 'Dossier2.id',
				126 => 'Dossier2.numdemrsa',
				127 => 'Dossier2.dtdemrsa',
				128 => 'Dossier2.dtdemrmi',
				129 => 'Dossier2.numdepinsrmi',
				130 => 'Dossier2.typeinsrmi',
				131 => 'Dossier2.numcominsrmi',
				132 => 'Dossier2.numagrinsrmi',
				133 => 'Dossier2.numdosinsrmi',
				134 => 'Dossier2.numcli',
				135 => 'Dossier2.numorg',
				136 => 'Dossier2.fonorg',
				137 => 'Dossier2.matricule',
				138 => 'Dossier2.statudemrsa',
				139 => 'Dossier2.typeparte',
				140 => 'Dossier2.ideparte',
				141 => 'Dossier2.fonorgcedmut',
				142 => 'Dossier2.numorgcedmut',
				143 => 'Dossier2.matriculeorgcedmut',
				144 => 'Dossier2.ddarrmut',
				145 => 'Dossier2.codeposanchab',
				146 => 'Dossier2.fonorgprenmut',
				147 => 'Dossier2.numorgprenmut',
				148 => 'Dossier2.dddepamut',
				149 => 'Dossier2.detaildroitrsa_id',
				150 => 'Dossier2.avispcgdroitrsa_id',
				151 => 'Dossier2.organisme_id',
				152 => 'Adresse2.id',
				153 => 'Adresse2.numvoie',
				154 => 'Adresse2.typevoie',
				155 => 'Adresse2.nomvoie',
				156 => 'Adresse2.complideadr',
				157 => 'Adresse2.compladr',
				158 => 'Adresse2.lieudist',
				159 => 'Adresse2.numcomrat',
				160 => 'Adresse2.numcomptt',
				161 => 'Adresse2.codepos',
				162 => 'Adresse2.locaadr',
				163 => 'Adresse2.pays',
				164 => 'Adresse2.canton',
				165 => 'Adresse2.typeres',
				166 => 'Adresse2.topresetr',
				167 => 'Situationdossierrsa2.id',
				168 => 'Situationdossierrsa2.dossier_id',
				169 => 'Situationdossierrsa2.etatdosrsa',
				170 => 'Situationdossierrsa2.dtrefursa',
				171 => 'Situationdossierrsa2.moticlorsa',
				172 => 'Situationdossierrsa2.dtclorsa',
				173 => 'Situationdossierrsa2.motirefursa',
				174 => 'Demandeur2.id',
				175 => 'Demandeur2.foyer_id',
				176 => 'Demandeur2.qual',
				177 => 'Demandeur2.nom',
				178 => 'Demandeur2.prenom',
				179 => 'Demandeur2.nomnai',
				180 => 'Demandeur2.prenom2',
				181 => 'Demandeur2.prenom3',
				182 => 'Demandeur2.nomcomnai',
				183 => 'Demandeur2.dtnai',
				184 => 'Demandeur2.rgnai',
				185 => 'Demandeur2.typedtnai',
				186 => 'Demandeur2.nir',
				187 => 'Demandeur2.topvalec',
				188 => 'Demandeur2.sexe',
				189 => 'Demandeur2.nati',
				190 => 'Demandeur2.dtnati',
				191 => 'Demandeur2.pieecpres',
				192 => 'Demandeur2.idassedic',
				193 => 'Demandeur2.numagenpoleemploi',
				194 => 'Demandeur2.dtinscpoleemploi',
				195 => 'Demandeur2.numfixe',
				196 => 'Demandeur2.numport',
				197 => 'Demandeur2.haspiecejointe',
				198 => 'Demandeur2.email',
			),
			'fields' => array(
				0 => 'Foyer.id',
				1 => 'Foyer.dossier_id',
				2 => 'Foyer.sitfam',
				3 => 'Foyer.ddsitfam',
				4 => 'Foyer.typeocclog',
				5 => 'Foyer.mtvallocterr',
				6 => 'Foyer.mtvalloclog',
				7 => 'Foyer.contefichliairsa',
				8 => 'Foyer.mtestrsa',
				9 => 'Foyer.raisoctieelectdom',
				10 => 'Foyer.regagrifam',
				11 => 'Foyer.haspiecejointe',
				12 => 'Dossier.id',
				13 => 'Dossier.numdemrsa',
				14 => 'Dossier.dtdemrsa',
				15 => 'Dossier.dtdemrmi',
				16 => 'Dossier.numdepinsrmi',
				17 => 'Dossier.typeinsrmi',
				18 => 'Dossier.numcominsrmi',
				19 => 'Dossier.numagrinsrmi',
				20 => 'Dossier.numdosinsrmi',
				21 => 'Dossier.numcli',
				22 => 'Dossier.numorg',
				23 => 'Dossier.fonorg',
				24 => 'Dossier.matricule',
				25 => 'Dossier.statudemrsa',
				26 => 'Dossier.typeparte',
				27 => 'Dossier.ideparte',
				28 => 'Dossier.fonorgcedmut',
				29 => 'Dossier.numorgcedmut',
				30 => 'Dossier.matriculeorgcedmut',
				31 => 'Dossier.ddarrmut',
				32 => 'Dossier.codeposanchab',
				33 => 'Dossier.fonorgprenmut',
				34 => 'Dossier.numorgprenmut',
				35 => 'Dossier.dddepamut',
				36 => 'Dossier.detaildroitrsa_id',
				37 => 'Dossier.avispcgdroitrsa_id',
				38 => 'Dossier.organisme_id',
				39 => 'Dossier.id',
				40 => 'Dossier.numdemrsa',
				41 => 'Dossier.dtdemrsa',
				42 => 'Dossier.dtdemrmi',
				43 => 'Dossier.numdepinsrmi',
				44 => 'Dossier.typeinsrmi',
				45 => 'Dossier.numcominsrmi',
				46 => 'Dossier.numagrinsrmi',
				47 => 'Dossier.numdosinsrmi',
				48 => 'Dossier.numcli',
				49 => 'Dossier.numorg',
				50 => 'Dossier.fonorg',
				51 => 'Dossier.matricule',
				52 => 'Dossier.statudemrsa',
				53 => 'Dossier.typeparte',
				54 => 'Dossier.ideparte',
				55 => 'Dossier.fonorgcedmut',
				56 => 'Dossier.numorgcedmut',
				57 => 'Dossier.matriculeorgcedmut',
				58 => 'Dossier.ddarrmut',
				59 => 'Dossier.codeposanchab',
				60 => 'Dossier.fonorgprenmut',
				61 => 'Dossier.numorgprenmut',
				62 => 'Dossier.dddepamut',
				63 => 'Dossier.detaildroitrsa_id',
				64 => 'Dossier.avispcgdroitrsa_id',
				65 => 'Dossier.organisme_id',
				66 => 'Adresse.id',
				67 => 'Adresse.numvoie',
				68 => 'Adresse.typevoie',
				69 => 'Adresse.nomvoie',
				70 => 'Adresse.complideadr',
				71 => 'Adresse.compladr',
				72 => 'Adresse.lieudist',
				73 => 'Adresse.numcomrat',
				74 => 'Adresse.numcomptt',
				75 => 'Adresse.codepos',
				76 => 'Adresse.locaadr',
				77 => 'Adresse.pays',
				78 => 'Adresse.canton',
				79 => 'Adresse.typeres',
				80 => 'Adresse.topresetr',
				81 => 'Situationdossierrsa.id',
				82 => 'Situationdossierrsa.dossier_id',
				83 => 'Situationdossierrsa.etatdosrsa',
				84 => 'Situationdossierrsa.dtrefursa',
				85 => 'Situationdossierrsa.moticlorsa',
				86 => 'Situationdossierrsa.dtclorsa',
				87 => 'Situationdossierrsa.motirefursa',
				88 => 'Demandeur.id',
				89 => 'Demandeur.foyer_id',
				90 => 'Demandeur.qual',
				91 => 'Demandeur.nom',
				92 => 'Demandeur.prenom',
				93 => 'Demandeur.nomnai',
				94 => 'Demandeur.prenom2',
				95 => 'Demandeur.prenom3',
				96 => 'Demandeur.nomcomnai',
				97 => 'Demandeur.dtnai',
				98 => 'Demandeur.rgnai',
				99 => 'Demandeur.typedtnai',
				100 => 'Demandeur.nir',
				101 => 'Demandeur.topvalec',
				102 => 'Demandeur.sexe',
				103 => 'Demandeur.nati',
				104 => 'Demandeur.dtnati',
				105 => 'Demandeur.pieecpres',
				106 => 'Demandeur.idassedic',
				107 => 'Demandeur.numagenpoleemploi',
				108 => 'Demandeur.dtinscpoleemploi',
				109 => 'Demandeur.numfixe',
				110 => 'Demandeur.numport',
				111 => 'Demandeur.haspiecejointe',
				112 => 'Demandeur.email',
				113 => 'Foyer2.id',
				114 => 'Foyer2.dossier_id',
				115 => 'Foyer2.sitfam',
				116 => 'Foyer2.ddsitfam',
				117 => 'Foyer2.typeocclog',
				118 => 'Foyer2.mtvallocterr',
				119 => 'Foyer2.mtvalloclog',
				120 => 'Foyer2.contefichliairsa',
				121 => 'Foyer2.mtestrsa',
				122 => 'Foyer2.raisoctieelectdom',
				123 => 'Foyer2.regagrifam',
				124 => 'Foyer2.haspiecejointe',
				125 => 'Dossier2.id',
				126 => 'Dossier2.numdemrsa',
				127 => 'Dossier2.dtdemrsa',
				128 => 'Dossier2.dtdemrmi',
				129 => 'Dossier2.numdepinsrmi',
				130 => 'Dossier2.typeinsrmi',
				131 => 'Dossier2.numcominsrmi',
				132 => 'Dossier2.numagrinsrmi',
				133 => 'Dossier2.numdosinsrmi',
				134 => 'Dossier2.numcli',
				135 => 'Dossier2.numorg',
				136 => 'Dossier2.fonorg',
				137 => 'Dossier2.matricule',
				138 => 'Dossier2.statudemrsa',
				139 => 'Dossier2.typeparte',
				140 => 'Dossier2.ideparte',
				141 => 'Dossier2.fonorgcedmut',
				142 => 'Dossier2.numorgcedmut',
				143 => 'Dossier2.matriculeorgcedmut',
				144 => 'Dossier2.ddarrmut',
				145 => 'Dossier2.codeposanchab',
				146 => 'Dossier2.fonorgprenmut',
				147 => 'Dossier2.numorgprenmut',
				148 => 'Dossier2.dddepamut',
				149 => 'Dossier2.detaildroitrsa_id',
				150 => 'Dossier2.avispcgdroitrsa_id',
				151 => 'Dossier2.organisme_id',
				152 => 'Adresse2.id',
				153 => 'Adresse2.numvoie',
				154 => 'Adresse2.typevoie',
				155 => 'Adresse2.nomvoie',
				156 => 'Adresse2.complideadr',
				157 => 'Adresse2.compladr',
				158 => 'Adresse2.lieudist',
				159 => 'Adresse2.numcomrat',
				160 => 'Adresse2.numcomptt',
				161 => 'Adresse2.codepos',
				162 => 'Adresse2.locaadr',
				163 => 'Adresse2.pays',
				164 => 'Adresse2.canton',
				165 => 'Adresse2.typeres',
				166 => 'Adresse2.topresetr',
				167 => 'Situationdossierrsa2.id',
				168 => 'Situationdossierrsa2.dossier_id',
				169 => 'Situationdossierrsa2.etatdosrsa',
				170 => 'Situationdossierrsa2.dtrefursa',
				171 => 'Situationdossierrsa2.moticlorsa',
				172 => 'Situationdossierrsa2.dtclorsa',
				173 => 'Situationdossierrsa2.motirefursa',
				174 => 'Demandeur2.id',
				175 => 'Demandeur2.foyer_id',
				176 => 'Demandeur2.qual',
				177 => 'Demandeur2.nom',
				178 => 'Demandeur2.prenom',
				179 => 'Demandeur2.nomnai',
				180 => 'Demandeur2.prenom2',
				181 => 'Demandeur2.prenom3',
				182 => 'Demandeur2.nomcomnai',
				183 => 'Demandeur2.dtnai',
				184 => 'Demandeur2.rgnai',
				185 => 'Demandeur2.typedtnai',
				186 => 'Demandeur2.nir',
				187 => 'Demandeur2.topvalec',
				188 => 'Demandeur2.sexe',
				189 => 'Demandeur2.nati',
				190 => 'Demandeur2.dtnati',
				191 => 'Demandeur2.pieecpres',
				192 => 'Demandeur2.idassedic',
				193 => 'Demandeur2.numagenpoleemploi',
				194 => 'Demandeur2.dtinscpoleemploi',
				195 => 'Demandeur2.numfixe',
				196 => 'Demandeur2.numport',
				197 => 'Demandeur2.haspiecejointe',
				198 => 'Demandeur2.email',
			),
		);

		/**
		 * Préparation du test.
		 */
		public function setUp() {
			parent::setUp();
			$this->Gestiondoublon = ClassRegistry::init( 'Gestiondoublon' );
		}

		/**
		 * Nettoyage postérieur au test.
		 */
		public function tearDown() {
			unset( $this->Gestiondoublon );
			parent::tearDown();
		}

		/**
		 * Test de la méthode Gestiondoublon::searchComplexes().
		 *
		 * @medium
		 */
		public function testSearchComplexes() {
			$result = $this->Gestiondoublon->searchComplexes();
			$expected = $this->emptySearch;
			$this->assertEqual( $result, $expected, var_export( $result, true ) );
		}
	}
?>
